In [1]:
import torch 
from torch import nn

In [2]:
import pandas as pd

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
data = pd.read_csv("./data/SMSSpamCollection", sep="\t",names=["type" , "message"])
data.head()
data["spam"]=data["type"]=="spam"

In [5]:
data.head()

   type                                            message   spam
0   ham  Go until jurong point, crazy.. Available only ...  False
1   ham                      Ok lar... Joking wif u oni...  False
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...   True
3   ham  U dun say so early hor... U c already then say...  False
4   ham  Nah I don't think he goes to usf, he lives aro...  False

In [6]:
data.drop("type",axis=1, inplace=True)

In [7]:
data.head()

                                             message   spam
0  Go until jurong point, crazy.. Available only ...  False
1                      Ok lar... Joking wif u oni...  False
2  Free entry in 2 a wkly comp to win FA Cup fina...   True
3  U dun say so early hor... U c already then say...  False
4  Nah I don't think he goes to usf, he lives aro...  False

In [8]:
cv = CountVectorizer(max_features=1000) #it will find 1000 most frequent word occuring in the document

In [15]:
messages = cv.fit_transform(data["message"])

In [16]:
print(messages.todense())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]